### ISSUE TITLE
Left nav not loading

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#58] opened 2023-06-15 08:43 UTC
When you navigate to some books, the left nav doesn't load at all. For example:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/30-xx/admin-guide/welcome/welcome

<img width="1472" alt="left-nav-not-loading" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/5e80a179-5bb1-4ab3-a7e9-2d4b5a66f306">

**Comment by maxakuru** [comment] 2023-06-20 21:24
@iansk this was caused by the `all-books` metadata entry not containing the "main book", ie. an entry that has the same path as the `book` column's path. 

I updated the metadata workbook, `all-books` sheet now has an optional `version` column. If included, it will only be included in that version's `all-books` entries. If undefined it will apply to all versions. This is just a shorthand to avoid duplicating the non-versioned books across all books in a product, the real issue is missing rows in the `all-books` sheet.

if you could help out by completing those rows that would be helpful

**Comment by iansk** [comment] 2023-06-21 19:32
@maxakuru I'll fill in these rows today

**Comment by iansk** [comment] 2023-06-22 05:02
@maxakuru I updated the `all-books` tab in the spreadsheet. Can you please take a look and see if I did it correctly?

Quick question: After making changes to the metadata sheet, I can go to the `.page` domain to see the impact of my changes, right?

**Comment by maxakuru** [comment] 2023-06-22 15:01
@iansk yes, `preview` in sidekick to view on .page, `publish` -> .live

I commented on the changes in #64

**Comment by maxakuru** [comment] 2023-06-24 00:53
looks like this is fixed, closing

**Closed by maxakuru** 2023-06-24 00:53 UTC
Labels: metadata-sheet
