### ISSUE TITLE
Load issue

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#42] opened 2023-06-13 05:57 UTC
I've noticed that sometimes after clicking on an item from the left nav bar, the chrome loads, but the content doesn't load. This only happens intermittently, and can't be reliably reproduced. If you then click to another page from the left nav, then back to the page that didn't load previously, the full content loads the second time around.

When the page doesn't load initially, I've tried waiting for up to a couple of minutes to see if it loads, but it stays in the same state.

**Comment by maxakuru** [comment] 2023-06-13 14:13
@iansk  do you have a page that you've found this occurs on most frequently so I can reproduce? 

otherwise, next time it happens could you open dev tools and take screenshots of the `console` & `network` tabs, along with any failed requests in the `network` tab?

**Comment by maxakuru** [comment] 2023-06-14 00:26
after looking into this a bit, I believe this is caused by section status not being updated after blocks are loaded in the section that contains `article` and `side-nav` blocks

if correct it will hopefully be fixed in #48 but I'll leave this open for a while just in case

**Comment by maxakuru** [comment] 2023-06-14 23:27
@iansk  seems this is fixed, if you see it again open a new issue

**Closed by maxakuru** 2023-06-14 23:27 UTC
Labels: bug
