### ISSUE TITLE
Some gifs don't load/render

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#194] opened 2023-10-07 18:31 UTC
On some pages, gif files load and render. On other pages, they don't.

For example, on this page, the gif loads:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/get-started/welcome-to-prisma-cloud

On this page, it doesn't:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/get-started/get-going

This page is an interesting case. One gif loads, but two don't:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/cloud-and-software-inventory/compute-workloads

**Comment by maxakuru** [comment] 2023-10-09 20:21
caused by incorrect mime types on some gifs coming from github.. possibly related to their size, but not positive.
fixed in https://github.com/hlxsites/prisma-cloud-docs/pull/118

docs where this occurred will need to be re-preview/published

**Closed by maxakuru** 2023-10-09 20:21 UTC
